services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"


  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    environment:
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=
      - GF_SMTP_PASSWORD=
      - GF_SMTP_FROM_ADDRESS=your_email@gmail.com
      - GF_SMTP_FROM_NAME=Grafana Alerts
      - GF_SMTP_SKIP_VERIFY=true



  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml

    networks:
      - monitoring


  aggregator:
    image: node:18
    container_name: aggregator
    working_dir: /app
    volumes:
      - path of aggregator.js:/app
    command: ["node", "aggregator.js"]
    networks:
      - monitoring
    depends_on:
      - prometheus
      - loki
    environment:
      - LOKI_URL=http://loki:3100
      - PROMETHEUS_URL=http://prometheus:9090

volumes:
  prometheus_data:
  grafana_data:
  loki_data:

networks:
  monitoring: