{
 "title": "Playwright ",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "location",
    "label": "location",
    "query": {
     "query": "label_values(playwright_tests_total,location)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average Resource Consumption",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{suite=\"flipkart\", location=~\"$location\"}"
    }
   ]
  },
  {
   "title": "Running Tests Live",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (suite) (playwright_test_running)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Consumption",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{suite=\"flipkart\", location=~\"$location\"}"
    }
   ]
  },
  {
   "title": "No. Of Success Test",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (location)(playwright_tests_total{status=\"success\", location=~\"$location\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No. Of Failed Test",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (location)(playwright_tests_total{status=\"failure\", location=~\"$location\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Tests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (location) (\n  playwright_tests_total{location=~\"$location\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running per Suite",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (suite,location) (playwright_test_running)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (location) (playwright_tests_total{status=\"success\", location=~\"$location\"})\n/\n  sum by (location) (playwright_tests_total{location=~\"$location\"})\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tests by Location",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (location) (\n  playwright_tests_total{location=~\"$location\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Test Duration (P95)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\n  sum by (le, location) (\n    rate(playwright_test_duration_seconds_bucket{location=~\"$location\"}[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}